Repository codeit-bootcamp-frontend/8-Sprint-Mission, pull requests merged in 2024-06, with the labels that each got.

#37 [김세환] sprint2
  faq/index.html
  images/goggle-icon.png
  images/header-panda.png
  images/ic_facebook.png
  images/ic_instagram.png
  images/ic_twitter.png
  images/ic_youtube.png
  images/invisible-btn.svg
  images/kakao-icon.png
  images/logo-txt.svg
  images/logo.svg
  images/main-bottom.png
  images/main_first.png
  images/main_second.png
  images/main_third.png
  images/visible-btn.svg
  index.html
  items/index.html
  login/index.html
  login/login.css
  login/signup/index.html
  login/signup/sign-up.css
  privacy/index.html
  style.css
Labels: 매운맛🔥

#46 [나윤주] Sprint2
  .DS_Store
  README.md
  assets/.DS_Store
  assets/css/style.css
  assets/css/style.css.map
  assets/fonts/.DS_Store
  assets/fonts/Pretendard-Bold.woff
  assets/fonts/Pretendard-Bold.woff2
  assets/fonts/Pretendard-Medium.woff
  assets/fonts/Pretendard-Medium.woff2
  assets/fonts/Pretendard-Regular.woff
  assets/fonts/Pretendard-Regular.woff2
  assets/fonts/Pretendard-SemiBold.woff
  assets/fonts/Pretendard-SemiBold.woff2
  assets/img/.DS_Store
  assets/img/Img_home_01.png
  assets/img/Img_home_02.png
  assets/img/Img_home_03.png
  assets/img/Img_home_bottom.png
  assets/img/Img_home_top.png
  assets/img/btn_visibility_on.svg
  assets/img/ic_facebook.svg
  assets/img/ic_google.svg
  assets/img/ic_instagram.svg
  assets/img/ic_kakao.svg
  assets/img/ic_twitter.svg
  assets/img/ic_youtube.svg
  assets/img/logo.svg
  assets/img/m-logo.svg
  assets/scss/_button.scss
  assets/scss/_fonts.scss
  assets/scss/_footer.scss
  assets/scss/_form.scss
  assets/scss/_header.scss
  assets/scss/_icon.scss
  assets/scss/_main.scss
  assets/scss/_reset.scss
  assets/scss/_variables.scss
  assets/scss/style.scss
  faq.html
  favicon.ico
  index.html
  items.html
  login.html
  privacy.html
  readmeSource/login.png
  readmeSource/main.png
  readmeSource/signup.png
  signup.html
Labels: 매운맛🔥

#38 [임귀태] Sprint2
  .gitignore
  assets/common/logo.svg
  assets/common/판다 얼굴.png
  assets/index/Img_home_01.png
  assets/index/Img_home_02-1.png
  assets/index/Img_home_03.png
  assets/index/Img_home_bottom.png
  assets/index/Img_home_top.png
  assets/index/ic_facebook.png
  assets/index/ic_instagram.png
  assets/index/ic_twitter.png
  assets/index/ic_youtube.png
  assets/login/Google-icon.svg
  assets/login/Kakao-icon.svg
  assets/login/btn_visibility_off_24px.svg
  assets/login/btn_visibility_on_24px.svg
  css/common.css
  css/index.css
  css/login.css
  html/faq.html
  html/index.html
  html/items.html
  html/login.html
  html/privacy.html
  html/signup.html
Labels: 매운맛🔥

#48 [장용한]Sprint2
  faq.html
  image/Img_home_bottom.png
  image/Img_home_top.png
  image/home1.png
  image/home2.png
  image/home3.png
  image/icon/Property 1=Default.png
  image/icon/Property 1=Variant2.png
  image/icon/google_icon.png
  image/icon/ic_facebook.png
  image/icon/ic_instagram.png
  image/icon/ic_twitter.png
  image/icon/ic_youtube.png
  image/icon/kakao_icon.png
  image/logo1.png
  image/logo2.png
  image/logo3x.png
  index.html
  item.html
  login.html
  login_style.css
  privacy.html
  signup.html
  signup_style.css
  style.css
Labels: 매운맛🔥

#39 [김강우] Sprint2
  .gitignore
  css/global.css
  css/style.css
  images/Img_home_01.png
  images/Img_home_01@2x.png
  images/Img_home_01@3x.png
  images/Img_home_02-1.png
  images/Img_home_02.png
  images/Img_home_02@2x.png
  images/Img_home_03.png
  images/Img_home_03@2x.png
  images/Img_home_03@3x.png
  images/Img_home_bottom.png
  images/Img_home_bottom@2x.png
  images/Img_home_bottom@3x.png
  images/Img_home_top.png
  images/Img_home_top@2x.png
  images/Img_home_top@3x.png
  images/Img_inquiry_empty.png
  images/Img_inquiry_empty.svg
  images/Img_inquiry_empty@2x.png
  images/Img_inquiry_empty@3x.png
  images/Img_reply_empty.png
  images/Img_reply_empty.svg
  images/Img_reply_empty@2x.png
  images/Img_reply_empty@3x.png
  images/btn_visibility_off_24px.png
  images/google_logo.png
  images/google_logo@2x.png
  images/google_logo@3x.png
  images/ic_facebook.svg
  images/ic_instagram.svg
  images/ic_twitter.svg
  images/ic_youtube.svg
  images/img_default.png
  images/img_default.svg
  images/img_default@2x.png
  images/img_default@3x.png
  images/kakao_logo.png
  images/kakao_logo@2x.png
  images/kakao_logo@3x.png
  images/logo.png
  images/logo@2x.png
  images/logo@3x.png
  index.html
  login/index.html
  signup/index.html
  test.md
Labels: 매운맛🔥

#13 [정인재] Sprint1
  .DS_Store
  FAQ/index.html
  img/.DS_Store
  img/Img_home_01.png
  img/Img_home_02.png
  img/Img_home_03.png
  img/Img_home_bottom.png
  img/Img_home_top.png
  img/ic_facebook.png
  img/ic_instagram.png
  img/ic_twitter.png
  img/ic_youtube.png
  img/pandaFace.png
  img/pandaLogo.png
  index.html
  items/index.html
  login/index.html
  privacy_policy/index.html
  style.css
Labels: 매운맛🔥

#70 [김종화] Sprint2
  css/style-index.css
  css/style-login.css
  css/style-signup.css
  faq.html
  image/Component 2.png
  image/Component 3.png
  image/Img_home_01.png
  image/Img_home_02.png
  image/Img_home_03.png
  image/Img_home_bottom.png
  image/Img_home_top.png
  image/Property 1=Variant3.png
  image/Property 1=Variant3@3x.png
  image/btn_large.png
  image/btn_large_gray.png
  image/btn_large_signup.png
  image/btn_small.png
  image/btn_visibility_on_24px.png
  image/ic_facebook.png
  image/ic_instagram.png
  image/ic_twitter.png
  image/ic_youtube.png
  image/title_ic.png
  index.html
  items.html
  login.html
  privacy.html
  signup.html
Labels: 매운맛🔥

#57 Part1 김준영 sprint2
  faq.html
  image/footer/facebook.png
  image/footer/instagram.png
  image/footer/twitter.png
  image/footer/youtube.png
  image/hidden.png
  image/hotitem.png
  image/logo.png
  image/panda-footer.png
  image/panda.png
  image/pandamarket.png
  image/register.png
  image/search.png
  image/social/google.png
  image/social/kakao.png
  index.html
  items.html
  login.html
  loginStyle.css
  privacy.html
  signup.html
  signupStyle.css
  style.css
Labels: 매운맛🔥

#42 [전주현]sprint2
  css/global.css
  css/home.css
  css/login_signup.css
  faq.html
  font/woff/Pretendard-Black.woff
  font/woff/Pretendard-Bold.woff
  font/woff/Pretendard-ExtraBold.woff
  font/woff/Pretendard-ExtraLight.woff
  font/woff/Pretendard-Light.woff
  font/woff/Pretendard-Medium.woff
  font/woff/Pretendard-Regular.woff
  font/woff/Pretendard-SemiBold.woff
  font/woff/Pretendard-Thin.woff
  font/woff2/Pretendard-Black.woff2
  font/woff2/Pretendard-Bold.woff2
  font/woff2/Pretendard-ExtraBold.woff2
  font/woff2/Pretendard-ExtraLight.woff2
  font/woff2/Pretendard-Light.woff2
  font/woff2/Pretendard-Medium.woff2
  font/woff2/Pretendard-Regular.woff2
  font/woff2/Pretendard-SemiBold.woff2
  font/woff2/Pretendard-Thin.woff2
  icon/ic_facebook.png
  icon/ic_google.png
  icon/ic_instagram.png
  icon/ic_kakao.png
  icon/ic_twitter.png
  icon/ic_youtube.png
  icon/visible_off.png
  icon/visible_on.png
  img/img_home_01.png
  img/img_home_02.png
  img/img_home_03.png
  img/img_home_bottom.png
  img/img_home_top.png
  img/logo.png
  img/logo_no_icon.png
  index.html
  items.html
  login.html
  privacy.html
  signup.html
  style.css
Labels: 매운맛🔥

#49 [서지훈]sprint2
  .DS_Store
  faq.html
  images/.DS_Store
  images/home/bottom-banner-image.png
  images/home/feature1-image.png
  images/home/feature2-image.png
  images/home/feature3-image.png
  images/home/hero-image.png
  images/icons/invisible.svg
  images/logo/favicon.ico
  images/logo/panda-market-logo.png
  images/social/facebook-logo.svg
  images/social/google-logo.png
  images/social/instagram-logo.svg
  images/social/kakao-logo.png
  images/social/twitter-logo.svg
  images/social/youtube-logo.svg
  index.html
  items.html
  login.html
  privacy.html
  signup.html
  styles/global.css
  styles/home.css
  styles/login.css
Labels: 매운맛🔥

#47 Basic 최원혁 sprint2
  img/btn_visibility_off_24px.png
  img/google.png
  img/kakao.png
  img/logo-login.png
  index.html
  login.html
  signUp.html
  style.css
Labels: 순한맛🐑

#33 [강성구] Sprint2
  README.md
  index.css
  index.html
  index.js
  login/login.css
  login/login.html
  readmeSource/127.0.0.1_5500_index.html.png
  readmeSource/login-page.png
  readmeSource/signin-page.png
  signup/signup.css
  signup/signup.html
  source/icons/google/google.png
  source/icons/google/google@2x.png
  source/icons/google/google@3x.png
  source/icons/kakao/kakao.png
  source/icons/kakao/kakao@2x.png
  source/icons/kakao/kakao@3x.png
  source/icons/password/btn_visibility_on_24px.png
  source/icons/password/btn_visibility_on_24px.svg
  source/icons/password/btn_visibility_on_24pxshow.svg
  source/images/logo/logo-login.png
  source/images/logo/logo-login@2x.png
  source/images/logo/logo-login@3x.png
Labels: 매운맛🔥

#28 [염정훈] Sprint2
  .github/sprint2/css/reset.css
  .github/sprint2/css/style.css
  .github/sprint2/faq.html
  .github/sprint2/images/.DS_Store
  .github/sprint2/images/banner-big.png
  .github/sprint2/images/banner-middle.png
  .github/sprint2/images/banner-small.png
  .github/sprint2/images/card01-big.png
  .github/sprint2/images/card01-middle.png
  .github/sprint2/images/card01-small.png
  .github/sprint2/images/card02-big.png
  .github/sprint2/images/card02-middle.png
  .github/sprint2/images/card02-small.png
  .github/sprint2/images/card03-big.png
  .github/sprint2/images/card03-middle.png
  .github/sprint2/images/card03-small.png
  .github/sprint2/images/i-facebook-big.png
  .github/sprint2/images/i-facebook-middle.png
  .github/sprint2/images/i-facebook-small.png
  .github/sprint2/images/i-facebook.svg
  .github/sprint2/images/i-google-big.png
  .github/sprint2/images/i-google-middle.png
  .github/sprint2/images/i-google.png
  .github/sprint2/images/i-instagram-big.png
  .github/sprint2/images/i-instagram-middle.png
  .github/sprint2/images/i-instagram-small.png
  .github/sprint2/images/i-instagram.svg
  .github/sprint2/images/i-kakao-big.png
  .github/sprint2/images/i-kakao-middle.png
  .github/sprint2/images/i-kakao.png
  .github/sprint2/images/i-password-off.png
  .github/sprint2/images/i-password-on.png
  .github/sprint2/images/i-twitter-big.png
  .github/sprint2/images/i-twitter-middle.png
  .github/sprint2/images/i-twitter-small.png
  .github/sprint2/images/i-twitter.svg
  .github/sprint2/images/i-youtube-big.png
  .github/sprint2/images/i-youtube-middle.png
  .github/sprint2/images/i-youtube-small.png
  .github/sprint2/images/i-youtube.svg
  .github/sprint2/images/keyvisual-big.png
  .github/sprint2/images/keyvisual-middle.png
  .github/sprint2/images/keyvisual-small.png
  .github/sprint2/images/logo-big.png
  .github/sprint2/images/logo-middle.png
  .github/sprint2/images/logo-small.png
  .github/sprint2/index.html
  .github/sprint2/items.html
  .github/sprint2/login.html
  .github/sprint2/privacy.html
  .github/sprint2/signup.html
Labels: 매운맛🔥

#44 [김주은] sprint2
  Img_home_01.png
  Img_home_02-1.png
  Img_home_03.png
  Img_home_bottom.png
  Img_home_top.png
  eye-off.png
  eye.png
  google-logo.png
  ic_facebook.png
  ic_facebook.svg
  ic_instagram.png
  ic_instagram.svg
  ic_twitter.png
  ic_twitter.svg
  ic_youtube.png
  ic_youtube.svg
  index.html
  kakaotalk-logo.png
  login.css
  login.html
  logo.png
  signup.css
  signup.html
  style.css
Labels: 순한맛🐑

#36 [김영주] Sprint2
  asset/font/PretendardVariable.woff2
  asset/icon/btn_visibility_off.png
  asset/icon/ic_eye_close.png
  asset/icon/ic_facebook.png
  asset/icon/ic_google.png
  asset/icon/ic_instagram.png
  asset/icon/ic_kakaotalk.png
  asset/icon/ic_twitter.png
  asset/icon/ic_youtube.png
  asset/img/Img_home_01.png
  asset/img/Img_home_02.png
  asset/img/Img_home_03.png
  asset/img/Img_home_bottom.png
  asset/img/Img_home_top.png
  asset/img/logo_pandamarket.png
  index.css
  index.html
  login.css
  login.html
  signup.html
Labels: 매운맛🔥

#58 [강효성] Sprint2
  faq.html
  index.html
  items.html
  login.html
  privacy.html
  sign.css
  signup.html
  style.css
Labels: 매운맛🔥

#40 [오정민] Sprint2
  .DS_Store
  .github/.DS_Store
  .gitignore
  Img_home_01.png
  Img_home_02.png
  Img_home_03.png
  Img_home_bottom.png
  Img_home_top.png
  Img_logo.png
  faq/index.html
  faq/style.css
  ic_facebook.png
  ic_instagram.png
  ic_twitter.png
  ic_youtube.png
  icon/btn_visibility_off_variant2.png
  icon/ic_google.png
  icon/ic_kakao.png
  icon/ic_password_disable.png
  index.html
  items/index.html
  items/style.css
  login/index.html
  login/style.css
  privacy/index.html
  privacy/style.css
  signup/index.html
  signup/style.css
  style.css
Labels: 매운맛🔥

#31 [김정현] Sprint2
  assets/JS/loginValidation.js
  assets/JS/signupValidation.js
  assets/JS/validation.js
  assets/images/Img_home_01.png
  assets/images/Img_home_01@2x.png
  assets/images/Img_home_01@3x.png
  assets/images/Img_home_02-1.png
  assets/images/Img_home_02.png
  assets/images/Img_home_02@2x.png
  assets/images/Img_home_03.png
  assets/images/Img_home_03@2x.png
  assets/images/Img_home_03@3x.png
  assets/images/Img_home_bottom.png
  assets/images/Img_home_bottom@2x.png
  assets/images/Img_home_bottom@3x.png
  assets/images/Img_home_top.png
  assets/images/Img_home_top@2x.png
  assets/images/Img_home_top@3x.png
  assets/images/Property 1=Typo@3x.png
  assets/images/Property 1=Variant3@3x.png
  assets/images/Property1=Typo@2x.png
  assets/images/Property1=Variant3@2x.png
  assets/images/google.png
  assets/images/hide_icon.png
  assets/images/ic_facebook.png
  assets/images/ic_facebook.svg
  assets/images/ic_facebook@2x.png
  assets/images/ic_facebook@3x.png
  assets/images/ic_instagram.png
  assets/images/ic_instagram.svg
  assets/images/ic_instagram@2x.png
  assets/images/ic_instagram@3x.png
  assets/images/ic_twitter.png
  assets/images/ic_twitter.svg
  assets/images/ic_twitter@2x.png
  assets/images/ic_twitter@3x.png
  assets/images/ic_youtube.png
  assets/images/ic_youtube.svg
  assets/images/ic_youtube@2x.png
  assets/images/ic_youtube@3x.png
  assets/images/kakao.png
  assets/images/logo.png
  assets/images/logo_type_text.png
  assets/images/register_logo.png
  assets/images/show_icon.png
  assets/register.css
  assets/reset.css
  assets/response.css
  assets/style.css
  faq.html
  index.html
  items.html
  privacy.html
  register/login.html
  register/signup.html
Labels: 매운맛🔥

#34 [염성진] Sprint2
  image/icon/btn_icon/visibilty_off.png
  image/icon/btn_icon/visibilty_on.png
  image/icon/ic_facebook.png
  image/icon/ic_google.png
  image/icon/ic_instagram.png
  image/icon/ic_kakao.png
  image/icon/ic_twitter.png
  image/icon/ic_youtube.png
  image/logo.png
  image/main/Img_home_01.png
  image/main/Img_home_02.png
  image/main/Img_home_03.png
  image/main/Img_home_bottom.png
  image/main/Img_home_top.png
  index.html
  join.css
  login.html
  signup.html
  style.css
  test.txt
Labels: 매운맛🔥

#54 [정원식] Sprint1
  faq/index.html
  index.css
  index.html
  items/index.html
  login/index.html
  privacy/index.html
  source/img/Img_home_01.png
  source/img/Img_home_02.png
  source/img/Img_home_03.png
  source/img/Img_home_bottom.png
  source/img/Img_home_top.png
  source/img/ic_facebook.png
  source/img/ic_instagram.png
  source/img/ic_twitter.png
  source/img/ic_youtube.png
  source/img/logo.png
  test.txt
Labels: 매운맛🔥

#65 [이승현]Sprint2
  image/btn_visibility_off.png
  image/btn_visibility_on.png
  image/google.png
  image/kakao.png
  image/logo.png
  index.css
  index.html
  javascript/login.js
  login.css
  login.html
  mediaQuery.css
  signup.css
  signup.html
  variable.css
Labels: 매운맛🔥

#55 [손재헌]sprint2
  Screenshot_20240531_172756_Chrome.jpg
  Screenshot_20240531_172806_Chrome.jpg
  Screenshot_20240531_172815_Chrome.jpg
  Screenshot_20240531_172822_Chrome.jpg
  Screenshot_20240531_182809_Chrome.jpg
  Screenshot_20240531_183313_Chrome.jpg
  imgs/Component2.png
  imgs/Component3.png
  imgs/EyeIcon.png
  imgs/EyeIconSlashed.png
  imgs/HomeLogo.png
  imgs/Img_home_01.png
  imgs/Img_home_02.png
  imgs/Img_home_03.png
  imgs/Img_home_bottom.png
  imgs/Img_home_top.png
  imgs/PandaFace.png
  imgs/ic_facebook.png
  imgs/ic_instagram.png
  imgs/ic_twitter.png
  imgs/ic_youtube.png
  imgs/signup_logo.png
  index.html
  login/index.html
  scripts/signup.js
  signup/index.html
  stylesheets/main_style.css
  stylesheets/signup_style.css
Labels: 매운맛🔥

#52 [김민찬] Sprint2
  assets/images/auth/auth-logo.png
  assets/images/auth/social-login-google.png
  assets/images/auth/social-login-kakao.png
  assets/images/auth/visibility-off.png
  assets/images/auth/visibility-on.png
  assets/images/home/home_bottom.png
  assets/images/home/home_feat1.png
  assets/images/home/home_feat2.png
  assets/images/home/home_feat3.png
  assets/images/home/home_top.png
  assets/images/home/ic_facebook.png
  assets/images/home/ic_instagram.png
  assets/images/home/ic_twitter.png
  assets/images/home/ic_youtube.png
  assets/images/home/logoAndTypo.png
  assets/images/home/typo.png
  index.html
  javascript/constants/paths.js
  javascript/constants/titles.js
  javascript/util/location.js
  pages/login/index.html
  pages/login/style.css
  pages/signup/index.html
  pages/signup/style.css
  style.css
  styles/@shared/init.css
  styles/@shared/mediaQuery.css
  styles/@shared/shared.css
  styles/auth/container.css
  styles/auth/form.css
  styles/auth/logo.css
  styles/auth/memberCheck.css
  styles/auth/social.css
  styles/home/brand.css
  styles/home/features.css
  styles/home/footer.css
  styles/home/header.css
Labels: 매운맛🔥

#56 [장혁수] sprint2
  faq.html
  home.html
  images/bigLogo.png
  images/ic_google.png.png
  images/ic_kakao.png.png
  images/non_visibility.png
  images/smallLogo.png
  index.html
  items.html
  login.html
  privacy.html
  signup.html
  stylesheets/form.css
  stylesheets/style.css
Labels: 미완성🫠

#68 [김준완] Sprint2
  banner_bt.png
  banner_image.png
  bottom_banner_img.png
  faq.html
  home_sec1_img.png
  home_sec2_img.png
  home_sec3_img.png
  home_style.css
  ic_eye.png
  ic_facebook.png
  ic_google.png
  ic_instagram.png
  ic_kakao.png
  ic_twitter.png
  ic_youtube.png
  image_logo.png
  image_logo_big.png
  index.html
  items.html
  login.html
  login_bt.png
  privacy.html
  script.js
  sign_style.css
  signup.html
  text_logo.png
  text_logo_big.png
Labels: 순한맛🐑

#64 [곽민조]Sprint2
  css/color_palette.css
  icon/ic_facebook.svg
  icon/ic_google-login.svg
  icon/ic_instagram.svg
  icon/ic_kakao-login.svg
  icon/ic_password-hide-mark.png
  icon/ic_password_eye.png
  icon/ic_twitter.svg
  icon/ic_youtube.svg
  icon/logo_pandaMarket.svg
  img/img_home_article_Item.png
  img/img_home_article_Register.png
  img/img_home_article_Search.png
  img/img_home_banner_bottom.png
  img/img_home_banner_top.png
  index.html
  login.css
  login.html
  mediaQuery.css
  script/script.js
  signup.html
  style.css
Labels: 매운맛🔥

#79 [장용한]Sprint3
  image/메타태그이미지.png
  image/판다마켓.png
  index.html
  login.html
  login_style.css
  signup.html
  signup_style.css
  style.css
Labels: 매운맛🔥

#80 [김세환] sprint3
  images/og-img.png
  index.html
  login/index.html
  login/login.css
  login/signup/index.html
  login/signup/sign-up.css
  style.css
Labels: 매운맛🔥

#81 [나윤주] Sprint3
  .DS_Store
  README.md
  assets/css/style.css
  assets/css/style.css.map
  assets/img/meta_thumb.png
  assets/scss/_button.scss
  assets/scss/_fonts.scss
  assets/scss/_footer.scss
  assets/scss/_form.scss
  assets/scss/_header.scss
  assets/scss/_main.scss
  assets/scss/_responsive.scss
  assets/scss/style.scss
  index.html
  login.html
  readmeSource/responsive.png
  readmeSource/thumb.png
  signup.html
Labels: 매운맛🔥

#76 [전주현]sprint3
  css/global.css
  css/home.css
  css/login_signup.css
  css/reset.css
  faq.html
  img/img_home_Hot_items.png
  img/img_home_Register.png
  img/img_home_Search.png
  img/link_thumbnail.png
  index.html
  items.html
  login.html
  privacy.html
  signup.html
Labels: 매운맛🔥

#78 [이형준]sprint3
  css/base/global.css
  css/home.css
  css/login.css
  images/img_home_items.png
  images/img_home_register.png
  images/img_home_search.png
  images/preview_img.png
  index.html
  pages/login/index.html
  pages/login/signup.html
Labels: 매운맛🔥

#74 [김정현] Sprint3
  assets/JS/loginValidation.js
  assets/JS/signupValidation.js
  assets/JS/validation.js
  assets/css/register.css
  assets/css/reset.css
  assets/css/response.css
  assets/css/style.css
  assets/images/Img_home_01@3x.png
  assets/images/Img_home_02.png
  assets/images/Img_home_03@3x.png
  assets/images/Img_home_bottom@2x.png
  assets/images/Img_home_bottom@3x.png
  assets/images/Img_home_top@2x.png
  assets/images/Img_home_top@3x.png
  assets/images/Property 1=Typo@3x.png
  assets/images/Property 1=Variant3@3x.png
  assets/images/banner.png
  assets/images/comment.png
  assets/images/google.png
  assets/images/hot_item.png
  assets/images/hot_item@2.png
  assets/images/ic_facebook.png
  assets/images/ic_facebook.svg
  assets/images/ic_facebook@2x.png
  assets/images/ic_facebook@3x.png
  assets/images/ic_instagram.png
  assets/images/ic_instagram.svg
  assets/images/ic_instagram@2x.png
  assets/images/ic_instagram@3x.png
  assets/images/ic_twitter.png
  assets/images/ic_twitter.svg
  assets/images/ic_twitter@2x.png
  assets/images/ic_twitter@3x.png
  assets/images/ic_youtube.png
  assets/images/ic_youtube.svg
  assets/images/ic_youtube@2x.png
  assets/images/ic_youtube@3x.png
  assets/images/icon.png
  assets/images/kakao.png
  assets/images/logo@2.png
  assets/images/mobile_logo.png
  assets/images/mobile_logo@2.png
  assets/images/og_image.jpg
  assets/images/register_item.png
  assets/images/register_item@2.png
  assets/images/search_item.png
  assets/images/search_item@2.png
  assets/reset.css
  assets/response.css
  index.html
  register/login.html
  register/signup.html
Labels: 매운맛🔥

#87 [염성진] Sprint3
  image/Img_for_meta_tag.png
  image/main/Img_home_for_sale_item.png
  image/main/Img_home_hot_item.png
  image/main/Img_home_item_search.png
  image/mini_logo.png
  index.html
  join.css
  login.html
  signup.html
  style.css
Labels: 매운맛🔥

#94 [이승현] Sprint3
  auth/auth.css
  auth/login.html
  auth/signup.html
  global/global.css
  global/variable.css
  image/og-img.jpg
  image/small-logo.png
  index.css
  index.html
  javascript/auth.js
  javascript/login.js
  login.html
  mediaQuery.css
  signup.css
  signup.html
Labels: 매운맛🔥

#90 [손재헌] sprint3
  imgs/meta_logo.png
  index.html
  login/index.html
  screenshots/sprint3/sprint3_1.JPG
  screenshots/sprint3/sprint3_2.JPG
  scripts/buttonValidationCheck.js
  scripts/filledInputsCheck.js
  scripts/mainPageEventHandler.js
  scripts/passwordVerifiedCheck.js
  scripts/signup.js
  scripts/signupIndex.js
  scripts/stdLib.js
  scripts/togglePasswordVisibility.js
  signup/index.html
  stylesheets/main_style.css
  stylesheets/signup_style.css
Labels: 매운맛🔥

#82 [정인재] sprint3
  .DS_Store
  index.html
  login/index.html
  login/style.css
  signup/style.css
  style.css
Labels: 매운맛🔥

#88 [김강우] sprint3
  .gitignore
  css/global.css
  css/style.css
  images/logo_text.png
  images/logo_text@2x.png
  index.html
  login/index.html
  signup/index.html
Labels: 매운맛🔥

#95 [정원식] Sprint3
  faq/index.html
  images/home/feature-search-img.png
  index.html
  items/index.html
  signin/index.html
  signup/index.html
  styles/global.css
  styles/home.css
  styles/sign.css
Labels: 매운맛🔥

#96 [조규진] Sprint3
  images/panda/panda_logo.png
  images/panda/pandamarket.png
  index.html
  login.html
  singin.html
  styles/auth.css
  styles/global.css
  styles/home.css
Labels: 매운맛🔥, 미완성🫠

#101 Part1 김준영 sprint3
  index.html
  style.css
Labels: 매운맛🔥

#92 [서지훈] sprint3
  faq.html
  images/home/feature-hotitem.png
  images/home/feature-register.png
  images/home/feature-search.png
  images/icons/.DS_Store
  images/logo/panda-market-logo.png
  images/logo/panda-market-logo.svg
  index.html
  items.html
  login.html
  privacy.html
  signup.html
  styles/global.css
  styles/home.css
  styles/login.css
Labels: 매운맛🔥

#75 [김영주] Sprint3
  .github/pull_request_template.md
  assets/fonts/PretendardVariable.woff2
  assets/icons/btn_visibility_off.png
  assets/icons/favicon_pandamarket.png
  assets/icons/ic_eye_close.png
  assets/icons/ic_facebook.png
  assets/icons/ic_google.png
  assets/icons/ic_instagram.png
  assets/icons/ic_kakaotalk.png
  assets/icons/ic_twitter.png
  assets/icons/ic_youtube.png
  assets/images/Img_home_01.png
  assets/images/Img_home_02.png
  assets/images/Img_home_03.png
  assets/images/Img_home_bottom.png
  assets/images/Img_home_top.png
  assets/images/logo_name.png
  assets/images/logo_pandamarket.png
  assets/images/og_pandamarket.png
  index.css
  index.html
  login.html
  signup.html
  styles/index.css
  styles/items.css
  styles/login.css
Labels: 매운맛🔥

#93 [강효성] Sprint3
  faq.html
  img/bottomPanda_img.png
  img/cacao_logo.png
  img/faq_text.png
  img/google_logo.png
  img/ic_facebook.png
  img/ic_instagram.png
  img/ic_password_visibility.png
  img/ic_twitter.png
  img/ic_youtube.png
  img/items_btn.png
  img/login_btn.png
  img/privacyPolicy_text.png
  img/sectionFirst_img.png
  img/sectionSecond_img.png
  img/sectionThird_img.png
  img/topPanda_img.png
  img/top_big_logo.png
  img/top_logo.png
  img/©codeit _2024_text.png
  index.html
  items.html
  login.html
  media.css
  privacy.html
  sign.css
  signup.html
  style.css
Labels: 매운맛🔥

#86 [이재완] Sprint3
  home.css
  images/logo/panda-market-logo-mobile-text.png
  images/logo/panda-market-logo-mobile.png
  index.html
  login.css
  login.html
  signup.html
Labels: 미완성🫠

#100 [장혁수] sprint3
  images/logo.png
  images/logo_text.png
  images/on_visibility.png
  index.html
  items.html
  login.html
  privacy.html
  signup.html
  stylesheets/form.css
  stylesheets/style.css
Labels: 미완성🫠

#89 [오정민] Sprint3
  .DS_Store
  .gitignore
  asset/font/pretendard/woff/Pretendard-Black.woff
  asset/font/pretendard/woff/Pretendard-Bold.woff
  asset/font/pretendard/woff/Pretendard-ExtraBold.woff
  asset/font/pretendard/woff/Pretendard-ExtraLight.woff
  asset/font/pretendard/woff/Pretendard-Light.woff
  asset/font/pretendard/woff/Pretendard-Medium.woff
  asset/font/pretendard/woff/Pretendard-Regular.woff
  asset/font/pretendard/woff/Pretendard-SemiBold.woff
  asset/font/pretendard/woff/Pretendard-Thin.woff
  asset/icon/btn_visibility_off_variant2.png
  asset/icon/btn_visibility_on_default.png
  asset/icon/ic_facebook.png
  asset/icon/ic_google.png
  asset/icon/ic_instagram.png
  asset/icon/ic_kakao.png
  asset/icon/ic_password_disable.png
  asset/icon/ic_plus.png
  asset/icon/ic_twitter.png
  asset/icon/ic_youtube.png
  asset/image/Img_home_01.png
  asset/image/Img_home_02.png
  asset/image/Img_home_03.png
  asset/image/Img_home_bottom.png
  asset/image/Img_home_top.png
  asset/image/Img_inquiry_empty.png
  asset/image/Img_logo.png
  asset/image/Img_logo_icon.png
  asset/image/Img_logo_text.png
  asset/image/Img_reply_empty.png
  asset/image/favicon.ico
  asset/image/img_badge.png
  asset/image/img_default.png
  faq/index.html
  index.html
  items/index.html
  login/index.html
  login/style.css
  privacy/index.html
  signup/index.html
  signup/style.css
  style.css
Labels: 매운맛🔥

#84 [김주은] sprint3
  eye-off.png
  eye.png
  global.css
  home.css
  image/banner-bottom.png
  image/banner-top.png
  image/eye-off.svg
  image/eye.svg
  image/google-logo.png
  image/hot-item.png
  image/ic_facebook.png
  image/ic_facebook.svg
  image/ic_instagram.png
  image/ic_instagram.svg
  image/ic_twitter.png
  image/ic_twitter.svg
  image/ic_youtube.png
  image/ic_youtube.svg
  image/kakaotalk-logo.png
  image/logo.png
  image/pandamarket.png
  image/register.png
  image/search.png
  index.html
  login-signup.css
  login.html
  signup.css
  signup.html
  style.css
Labels: 매운맛🔥

#85 [염정훈] Sprint3
  .github/sprint3/css/reset.css
  .github/sprint3/css/style.css
  .github/sprint3/faq.html
  .github/sprint3/images/.DS_Store
  .github/sprint3/images/banner-big.png
  .github/sprint3/images/banner-middle.png
  .github/sprint3/images/banner-small.png
  .github/sprint3/images/card01-big.png
  .github/sprint3/images/card01-middle.png
  .github/sprint3/images/card01-small.png
  .github/sprint3/images/card02-big.png
  .github/sprint3/images/card02-middle.png
  .github/sprint3/images/card02-small.png
  .github/sprint3/images/card03-big.png
  .github/sprint3/images/card03-middle.png
  .github/sprint3/images/card03-small.png
  .github/sprint3/images/i-facebook-big.png
  .github/sprint3/images/i-facebook-middle.png
  .github/sprint3/images/i-facebook-small.png
  .github/sprint3/images/i-facebook.svg
  .github/sprint3/images/i-google-big.png
  .github/sprint3/images/i-google-middle.png
  .github/sprint3/images/i-google.png
  .github/sprint3/images/i-instagram-big.png
  .github/sprint3/images/i-instagram-middle.png
  .github/sprint3/images/i-instagram-small.png
  .github/sprint3/images/i-instagram.svg
  .github/sprint3/images/i-kakao-big.png
  .github/sprint3/images/i-kakao-middle.png
  .github/sprint3/images/i-kakao.png
  .github/sprint3/images/i-password-off.png
  .github/sprint3/images/i-password-on.png
  .github/sprint3/images/i-twitter-big.png
  .github/sprint3/images/i-twitter-middle.png
  .github/sprint3/images/i-twitter-small.png
  .github/sprint3/images/i-twitter.svg
  .github/sprint3/images/i-youtube-big.png
  .github/sprint3/images/i-youtube-middle.png
  .github/sprint3/images/i-youtube-small.png
  .github/sprint3/images/i-youtube.svg
  .github/sprint3/images/keyvisual-big.png
  .github/sprint3/images/keyvisual-middle.png
  .github/sprint3/images/keyvisual-small.png
  .github/sprint3/images/logo-big.png
  .github/sprint3/images/logo-middle.png
  .github/sprint3/images/logo-small.png
  .github/sprint3/images/logo-txt.png
  .github/sprint3/images/thumbnail-big.png
  .github/sprint3/images/thumbnail-middle.png
  .github/sprint3/images/thumbnail.png
  .github/sprint3/index.html
  .github/sprint3/items.html
  .github/sprint3/login.html
  .github/sprint3/privacy.html
  .github/sprint3/signup.html
Labels: 매운맛🔥

#83 [강성구] Sprint3
  README.md
  index.css
  index.html
  login/login.css
  readmeSource/landing-mobile_version.png
  readmeSource/landing-pc_version.png
  readmeSource/landing-tablet_version.png
  readmeSource/login-mobile_version.png
  readmeSource/login-page.png
  readmeSource/login-pc_version.png
  readmeSource/signin-mobile_version.png
  readmeSource/signin-page.png
  readmeSource/signin-pc_version.png
  signup/signup.css
  source/images/logo/logo-mobile.png
Labels: 매운맛🔥

#73 [옥승현]sprint1
  panda/faq.html
  panda/images/home/img_home_01.png
  panda/images/home/img_home_02.png
  panda/images/home/img_home_03.png
  panda/images/home/img_home_bottom.png
  panda/images/home/img_home_top.png
  panda/images/logo/favicon.jpg
  panda/images/logo/logo.png
  panda/images/social/ic_facebook.png
  panda/images/social/ic_instagram.png
  panda/images/social/ic_twitter.png
  panda/images/social/ic_youtube.png
  panda/index.html
  panda/items.html
  panda/login.html
  panda/privacy.html
  panda/styles/style.css
Labels: 매운맛🔥

#103 [김준완] Sprint3
  .gitignore
  banner_bt.png
  banner_image.png
  bottom_banner_img.png
  faq.html
  home_sec1_img.png
  home_sec2_img.png
  home_sec3_img.png
  home_style.css
  ic_eye.png
  ic_facebook.png
  ic_google.png
  ic_instagram.png
  ic_kakao.png
  ic_twitter.png
  ic_youtube.png
  image_logo.png
  image_logo_big.png
  index.html
  items.html
  login.html
  login_bt.png
  privacy.html
  script.js
  sign_style.css
  signup.html
  text_logo.png
  text_logo_big.png
Labels: 순한맛🐑

#106 [손재헌] sprint4
  login/index.html
  scripts/buttonValidationCheck.js
  scripts/constLib.js
  scripts/emailValidationCheck.js
  scripts/filledInputsCheck.js
  scripts/mainPageEventHandler.js
  scripts/nicknameEmptyCheck.js
  scripts/passwordFormatCheck.js
  scripts/passwordVerifiedCheck.js
  scripts/signup.js
  scripts/signupEventHandler.js
  scripts/signupIndex.js
  signup/index.html
  stylesheets/signup_style.css
Labels: 매운맛🔥

#110 [강성구] Sprint4
  README.md
  index.html
  login/login.css
  login/login.html
  login/login.js
  modules/handleBtnActive.js
  modules/handleError.js
  modules/handleForm.js
  modules/passwordVisibility.js
  modules/state.js
  modules/validations.js
  readmeSource/landing-mobile_version.png
  readmeSource/landing-pc_version.png
  readmeSource/landing-tablet_version.png
  readmeSource/login-mobile_version.png
  readmeSource/login-pc_version.png
  readmeSource/loginAllowed.png
  readmeSource/loginError1.png
  readmeSource/loginError2.png
  readmeSource/loginVisibility.png
  readmeSource/signin-mobile_version.png
  readmeSource/signin-pc_version.png
  readmeSource/signupAllowed.png
  readmeSource/signupError1.png
  readmeSource/signupError2.png
  signup/signup.css
  signup/signup.html
  signup/signup.js
Labels: 매운맛🔥

#111 [김강우] sprint4
  .gitignore
  css/global.css
  css/style.css
  images/btn_visibility_on_24px.png
  index.html
  items/index.html
  login/index.html
  main.js
  signup/index.html
  test.md
  utils/valid.js
Labels: 매운맛🔥

#112 [정원식] Sprint4
  scripts/signin.js
  scripts/signup.js
  signin/index.html
  signup/index.html
  styles/sign.css
Labels: 매운맛🔥

#117 [장용한] Sprint4
  image/icon/PropertyDefault.png
  image/icon/PropertyVariant.png
  index.js
  login.html
  login_style.css
  signin.html
  signup.html
  signup_style.css
  style.css
Labels: 매운맛🔥

#130 [서지훈]sprint4
  images/icons/visible.svg
  index.html
  login.html
  scripts/login.js
  scripts/loginValidation.js
  scripts/signup.js
  signup.html
  styles/global.css
  styles/login.css
Labels: 매운맛🔥

#124 [장혁수] sprint4
  images/bigLogo.png
  images/logo1.png
  images/logo2.png
  images/logo3.png
  images/logo_text1.png
  images/og-image.png
  images/smallLogo.png
  index.html
  login.html
  login.js
  signup.html
  stylesheets/form.css
  stylesheets/style.css
Labels: 미완성🫠

#114 [김준완] sprint4
  .gitignore
  README.md
  home_style.css
  ic_eye.png
  index.html
  listeners.js
  login.html
  package-lock.json
  package.json
  public/favicon.ico
  public/index.html
  public/logo192.png
  public/logo512.png
  public/manifest.json
  public/robots.txt
  script.js
  sign_style.css
  signin.html
  signup.html
  src/App.css
  src/App.js
  src/App.test.js
  src/index.css
  src/index.js
  src/logo.svg
  src/reportWebVitals.js
  src/setupTests.js
Labels: 순한맛🐑

#128 [임귀태] Sprint4
  .gitignore
  JS/auth.js
  JS/index.js
  css/index.css
  css/login.css
  css/login.css.map
  html/index.html
  html/login.html
  html/signin.html
  html/signup.html
  scss/index.scss
  scss/login.scss
Labels: 매운맛🔥

#136 [곽민조]Sprint3
  css/color_palette.css
  css/empty-space.css
  css/mediaQuerys.css
  img/img_pandaMarket.png
  index.html
  login.css
  login.html
  mediaQuery.css
  script/script.js
  signup.html
  style.css
Labels: 매운맛🔥

#127 [김주은] sprint4
  CSS/global.css
  CSS/home.css
  CSS/login-signup.css
  CSS/reset.css
  JS/login.js
  JS/signup.js
  index.html
  login.html
  signup.html
Labels: 매운맛🔥

#119 :dizzy: Sprint Mission 4 Complete
  login.html
  login.js
  loginStyle.css
  signin.html
  signup.html
  signup.js
  signupStyle.css
Labels: 매운맛🔥

#113 [오정민] Sprint4
  asset/font/pretendard/woff/fonts.css
  asset/icon/btn_visibility_off.png
  asset/icon/btn_visibility_on.png
  faq/style.css
  index.html
  items/style.css
  login/index.html
  login/script.js
  login/style.css
  privacy/style.css
  signup/index.html
  signup/script.js
  signup/style.css
  style.css
Labels: 매운맛🔥

#109 [나윤주] sprint4
  .DS_Store
  .gitignore
  README.md
  assets/.DS_Store
  assets/css/style.css
  assets/css/style.css.map
  assets/img/.DS_Store
  assets/img/btn_visibility_off.svg
  assets/img/btn_visibility_on.svg
  assets/js/form-validation.js
  assets/js/login.js
  assets/js/password-toggle.js
  assets/js/signup.js
  assets/js/signup2.js
  assets/scss/_form.scss
  assets/scss/_header.scss
  assets/scss/_icon.scss
  assets/scss/_responsive.scss
  login.html
  readmeSource/valid_error.png
  readmeSource/valid_success.png
  signup.html
Labels: 매운맛🔥

#115 [이형준]sprint4
  css/login.css
  js/button.js
  js/input.js
  js/main.js
  js/pw_visibility.js
  pages/login/index.html
  pages/login/signup.html
Labels: 매운맛🔥

#126 [김민찬] Sprint4
  assets/images/home/home_feat1.png
  assets/images/home/home_feat2.png
  assets/images/home/home_feat3.png
  assets/images/meta/ogImage.png
  index.html
  javascript/auth/form.js
  javascript/auth/password.js
  javascript/router/router.js
  javascript/util/location.js
  javascript/utils/location.js
  pages/items/index.html
  pages/login/index.html
  pages/login/style.css
  pages/signup/index.html
  pages/signup/style.css
  style.css
  styles/@shared/init.css
  styles/@shared/mediaQuery.css
  styles/auth/container.css
  styles/auth/form.css
  styles/auth/mediaQuery.css
  styles/home/brand.css
  styles/home/features.css
  styles/home/footer.css
  styles/home/mediaQuery.css
Labels: 매운맛🔥

#134 [강효성] Sprint4
  login.html
  media.css
  sign.js
  signup.html
  style.css
Labels: 미완성🫠

#116 [김종화] sprint4
  css/style-index.css
  css/style-login.css
  css/style-signup.css
  index.html
  js/verifyLogin.js
  js/verifySignup.js
  login.html
  signin.html
  signup.html
Labels: 매운맛🔥

#131 [이승현] Sprint4
  auth/auth.css
  auth/login.html
  auth/signup.html
  javascript/auth.js
  javascript/authErrorHandler.js
  javascript/password-toggle.js
Labels: 매운맛🔥

#137 [엄세환] sprint4
  .vscode/settings.json
  Property 1=Variant3.svg
  icons/Property 1=Variant3.svg
  images/Img_home_01.svg
  images/Img_home_02.svg
  images/Img_home_03.svg
  images/Img_home_bottom.svg
  images/Img_home_top.svg
  images/home/bottom-banner-image.png
  images/home/feature1-image.png
  images/home/feature2-image.png
  images/home/feature3-image.png
  images/home/hero-image.png
  images/icons/eye-invisible.svg
  images/icons/eye-visible.svg
  images/logo/favicon.ico
  images/logo/logo.svg
  images/logo/og-image.png
  images/social/facebook-logo.svg
  images/social/google-logo.png
  images/social/instagram-logo.svg
  images/social/kakao-logo.png
  images/social/twitter-logo.svg
  images/social/youtube-logo.svg
  index.html
  login.html
  scripts/signin.js
  scripts/signup.js
  scripts/validation.js
  signin.html
  signup.html
  style.css
  styles/auth.css
  styles/global.css
  styles/home.css
Labels: 매운맛🔥

#125 Basic 최원혁 sprint4
  index.html
  index.js
  login.html
  signIn.html
  signUp.html
  style.css
Labels: 미완성🫠

#118 [정인재] Sprint4
  JS-MODULES/loginInput.js
  JS-MODULES/signupInput.js
  index.html
  login/index.html
  login/style.css
  signin/index.html
  signup/index.html
  signup/style.css
  style.css
Labels: 매운맛🔥

#104 [김정현] Sprint4
  assets/JS/errorMessage.js
  assets/JS/loginValidation.js
  assets/JS/signupValidation.js
  assets/JS/validation.js
  assets/css/register.css
  assets/css/reset.css
  assets/css/response.css
  assets/css/style.css
  register/login.html
  register/signup.html
Labels: 매운맛🔥

#121 [김영주] Sprint4
  assets/icons/btn_visibility.png
  global.css
  index.html
  pages/faq.html
  pages/items/items.css
  pages/items/items.html
  pages/login/login.css
  pages/login/login.html
  pages/privacy.html
  pages/signup/signup.html
  validate.js
Labels: 매운맛🔥

#107 [전주현]sprint4
  css/global.css
  css/login_signup.css
  faq.html
  icon/visible_off.png
  icon/visible_on.png
  index.html
  items.html
  js/login_signup.js
  login.html
  privacy.html
  signup.html
Labels: 매운맛🔥

#123 [김우성] Sprint 4
  sprint/.gitignore
  sprint/assets/img/banner_bottom/1x.png
  sprint/assets/img/banner_bottom/3x.png
  sprint/assets/img/banner_bottom/4x.png
  sprint/assets/img/banner_top/1x.png
  sprint/assets/img/banner_top/3x.png
  sprint/assets/img/banner_top/4x.png
  sprint/assets/img/contents/01/1x.png
  sprint/assets/img/contents/01/3x.png
  sprint/assets/img/contents/01/4x.png
  sprint/assets/img/contents/02/1x.png
  sprint/assets/img/contents/02/3x.png
  sprint/assets/img/contents/02/4x.png
  sprint/assets/img/contents/03/1x.png
  sprint/assets/img/contents/03/3x.png
  sprint/assets/img/contents/03/4x.png
  sprint/assets/logo_facebook.svg
  sprint/assets/logo_none_txt.svg
  sprint/assets/svg/ic_facebook.svg
  sprint/assets/svg/ic_google.svg
  sprint/assets/svg/ic_instagram.svg
  sprint/assets/svg/ic_kakaotalk.svg
  sprint/assets/svg/ic_panda.svg
  sprint/assets/svg/ic_visibility_off.svg
  sprint/assets/svg/ic_visibility_on.svg
  sprint/assets/svg/ic_x.svg
  sprint/assets/svg/ic_youtube.svg
  sprint/assets/svg/logo.svg
  sprint/component.css
  sprint/index.css
  sprint/index.html
  sprint/main.css
  sprint/main.js
  sprint/src/Login.css
  sprint/src/Login.html
  sprint/src/Root.js
  sprint/src/constant/Event.js
  sprint/src/constant/ID.js
  sprint/src/constant/Message.js
  sprint/src/constant/Regex.js
  sprint/src/pages/Home.css
  sprint/src/pages/Home.js
  sprint/src/pages/sign/In.css
  sprint/src/pages/sign/In.js
  sprint/src/pages/sign/Up.css
  sprint/src/pages/sign/Up.js
  sprint/src/utils/CustomElement.js
  sprint/src/utils/CustomRouter.js
Labels: 매운맛🔥

#120 [염성진] Sprint4
  .vscode/launch.json
  index.html
  items.html
  join.css
  login-signup.js
  login.html
  signin.html
  signup.html
  style.css
Labels: 매운맛🔥

#132 [최영선] Sprint4
  images/carrot_panda.png
  images/panda_face.png
  index.html
  login.css
  login.html
  login_mobile.css
  login_tablet.css
  login_valid_check.js
  signin.html
  signup.css
  signup.html
  signup_mobile.css
  signup_tablet.css
  signup_valid_check.js
Labels: 매운맛🔥

#133 [김리나] Sprint 4
  README.md
  img/bg_bottom.png
  img/bg_top.png
  img/facebook.png
  img/favicon.ico
  img/home_1.png
  img/home_2.png
  img/home_3.png
  img/insta.png
  img/logoimg.png
  img/logotxt.png
  img/twiter.png
  img/youtube.png
  panda/css/global.css
  panda/css/login.css
  panda/css/signup.css
  panda/css/style.css
  panda/html/index.html
  panda/html/login.html
  panda/html/signup.html
  panda/img/login/google.png
Labels: 미완성🫠

#135 [조규진]Sprint4
  faq.html
  images/panda/panda.png
  images/panda/panda_logo.png
  images/panda/pandamarket.png
  images/pandamarket/favicon.ico
  images/pandamarket/logo.svg
  images/pandamarket/og-image.png
  index.html
  items.html
  login.html
  privacy.html
  scripts/auth.js
  singin.html
  styles/auth.css
  styles/global.css
  styles/home.css
  styles/panda.css
  styles/pandaaaa.css
Labels: 미완성🫠

#138 [곽민조] sprint4
  icon/ic_password-eye.svg
  icon/ic_password-hide-eye.svg
  icon/ic_password-hide-mark.png
  icon/ic_password_eye.png
  index.html
  items.html
  login.css
  login.html
  script/author_js/ErrorMessage.js
  script/author_js/activeBtnByInputsValid.js
  script/author_js/checkValid.js
  script/buttonManager.js
  script/inputManager.js
  script/script.js
  signup.html
Labels: 매운맛🔥

#144 [장혁수] sprint5
  package-lock.json
  public/favicon.ico
  public/index.html
  public/logo192.png
  public/logo512.png
  public/manifest.json
  public/robots.txt
  src/App.css
  src/App.js
  src/App.test.js
  src/Header.css
  src/Header.js
  src/Items.js
  src/fonts/Pretendard-Regular.ttf
  src/images/logo1.png
  src/images/logo_text.png
  src/index.css
  src/index.js
  src/items.css
  src/logo.svg
  src/reportWebVitals.js
  src/setupTests.js
Labels: 미완성🫠

#146 [김준완] Sprint5
  ic_eye.png
  listeners.js
  login.html
  package-lock.json
  script.js
  sign_style.css
  signin.html
  signup.html
  src/App.js
Labels: 미완성🫠

#160 [김리나] Sprint5
  src/App.js
  src/global.css
  src/market/market.css
  src/market/market.jsx
Labels: 미완성🫠

#167 [이재완] Sprint5
  .gitignore
  public/favicon.ico
  public/index.html
  public/logo192.png
  public/logo512.png
  public/manifest.json
  public/robots.txt
  src/App.css
  src/App.js
  src/App.test.js
  src/assets/images/Img_logo_icon.png
  src/assets/images/Img_logo_text.png
  src/assets/images/ic_heart_empty.png
  src/assets/images/ic_heart_full.png
  src/components/AllProductList.css
  src/components/AllProductList.js
  src/components/Menu.css
  src/components/Menu.js
  src/components/Nav.css
  src/components/Nav.js
  src/components/ProductListItem.css
  src/components/ProductListItem.js
  src/index.css
  src/index.js
  src/logo.svg
  src/reportWebVitals.js
  src/setupTests.js
Labels: 미완성🫠

#143 [손재헌] Sprint5
  public/favicon.ico
  public/index.html
  public/logo192.png
  public/logo512.png
  public/manifest.json
  public/robots.txt
  src/App.css
  src/App.js
  src/App.test.js
  src/api.js
  src/assets/HomeLogo.png
  src/assets/dropdown_arrow.svg
  src/assets/ic_heart.svg
  src/assets/ic_search.svg
  src/components/App.js
  src/components/header/Header.css
  src/components/header/Header.js
  src/components/header/HomeLogo.js
  src/components/header/LoginButton.css
  src/components/header/LoginButton.js
  src/components/header/Nav.css
  src/components/header/Nav.js
  src/components/header/NavTab.css
  src/components/header/NavTab.js
  src/components/main/BestSection.css
  src/components/main/BestSection.js
  src/components/main/Card.css
  src/components/main/Card.js
  src/components/main/ItemsSection.css
  src/components/main/ItemsSection.js
  src/components/main/Main.css
  src/components/main/Main.js
  src/index.css
  src/index.js
  src/logo.svg
  src/reportWebVitals.js
  src/setupTests.js
Labels: 매운맛🔥

#168 React 정인재 sprint5
  .github/delete-merged-branch-config.yml
  public/favicon.ico
  public/index.html
  public/logo192.png
  public/logo512.png
  public/manifest.json
  public/robots.txt
  src/App.css
  src/App.js
  src/App.test.js
  src/api.js
  src/components/App.css
  src/components/App.js
  src/components/BestProductList.css
  src/components/BestProductList.js
  src/components/Button.css
  src/components/Button.js
  src/components/ProductList.css
  src/components/ProductList.js
  src/components/Topbar.css
  src/components/Topbar.js
  src/img/logo.png
  src/index.css
  src/index.js
  src/logo.svg
  src/reportWebVitals.js
  src/setupTests.js
Labels: 미완성🫠

#155 [장용한] Sprint5
  package-lock.json
  package.json
  public/favicon.ico
  public/index.html
  public/logo192.png
  public/logo512.png
  public/manifest.json
  public/robots.txt
  src/App.css
  src/App.js
  src/App.test.js
  src/ItemAPI.js
  src/Layout/Header.css
  src/Layout/Header.jsx
  src/Layout/UI/Carousel.css
  src/Layout/UI/Carousel.jsx
  src/Layout/UI/SearchBar.css
  src/Layout/UI/SearchBar.jsx
  src/images/icons/arrow_left.svg
  src/images/icons/arrow_right.svg
  src/images/icons/ic_heart.svg
  src/images/icons/ic_search.svg
  src/images/icons/ic_sort.svg
  src/images/logo/logo.svg
  src/index.css
  src/index.js
  src/logo.svg
  src/pages/AllCard.jsx
  src/pages/BestAllCard.jsx
  src/pages/BestCard.js
  src/pages/Card.js
  src/pages/ItemCard.jsx
  src/pages/MarketPage.jsx
  src/pages/utils.js
  src/reportWebVitals.js
  src/setupTests.js
Labels: 미완성🫠

#163 [임귀태] Sprint5
  .gitignore
  .vscode/settings.json
  package-lock.json
  package.json
  public/favicon.ico
  public/index.html
  public/logo192.png
  public/logo512.png
  public/manifest.json
  public/robots.txt
  src/App.css
  src/App.js
  src/App.test.js
  src/assets/HomePage/Img_home_01.png
  src/assets/HomePage/Img_home_02.png
  src/assets/HomePage/Img_home_03.png
  src/assets/HomePage/Img_home_bottom.png
  src/assets/HomePage/Img_home_top.png
  src/assets/HomePage/ic_facebook.png
  src/assets/HomePage/ic_instagram.png
  src/assets/HomePage/ic_twitter.png
  src/assets/HomePage/ic_youtube.png
  src/assets/ItemsPage/arrow_left.svg
  src/assets/ItemsPage/arrow_right.svg
  src/assets/ItemsPage/ic_heart.svg
  src/assets/ItemsPage/ic_search.svg
  src/assets/ItemsPage/ic_sort.svg
  src/assets/LoginPage/Google-icon.svg
  src/assets/LoginPage/Kakao-icon.svg
  src/assets/LoginPage/btn_visibility_off_24px.svg
  src/assets/LoginPage/btn_visibility_on_24px.svg
  src/assets/common/logo-mobile.svg
  src/assets/common/logo.svg
  src/assets/common/meta-image.png
  src/assets/common/판다 얼굴.svg
  src/index.css
  src/index.js
  src/js/auth.js
  src/js/itemApi.js
  src/logo.svg
  src/pages/AddItemPage/AddItemPage.jsx
  src/pages/AddItemPage/AddItemPage.scss
  src/pages/HomePage/HomePage.jsx
  src/pages/HomePage/HomePage.scss
  src/pages/ItemsPage/ItemsPage.jsx
  src/pages/ItemsPage/ItemsPage.scss
  src/pages/ItemsPage/components/AllItemsSection.jsx
  src/pages/ItemsPage/components/BestItemsSection.jsx
  src/pages/ItemsPage/components/ItemCard.jsx
  src/pages/LoginPage/LoginPage.html
  src/pages/LoginPage/LoginPage.jsx
  src/pages/LoginPage/LoginPage.scss
  src/pages/NOT_NOW/FaqPage/faq.html
  src/pages/NOT_NOW/PrivacyPage/privacy.html
  src/pages/NOT_NOW/SiginInPage/signin.html
  src/pages/SignupPage/SignupPage.jsx
  src/pages/SignupPage/signup.html
  src/reportWebVitals.js
  src/setupTests.js
  src/styles/common.scss
Labels: 매운맛🔥, 미완성🫠

#158 [이승현] Sprint5
  package-lock.json
  package.json
  public/favicon.ico
  public/index.html
  public/logo192.png
  public/logo512.png
  public/manifest.json
  public/robots.txt
  src/App.css
  src/App.js
  src/App.test.js
  src/api/api.js
  src/components/HeaderComponent/Header.css
  src/components/HeaderComponent/Header.jsx
  src/components/Pagination/Pagination.css
  src/components/Pagination/Pagination.jsx
  src/global.css
  src/images/defaultImg.jpeg
  src/images/logo/logo1x.png
  src/images/logo/logo2x.png
  src/images/logo/logo3x.png
  src/index.css
  src/index.js
  src/logo.svg
  src/pages/AddItemPage/AddItemPage.css
  src/pages/AddItemPage/AddItemPage.jsx
  src/pages/HomePage/HomePage.css
  src/pages/HomePage/HomePage.jsx
  src/pages/MarketPage/MarketPage.css
  src/pages/MarketPage/MarketPage.jsx
  src/pages/MarketPage/components/BestProducts/BestProducts.css
  src/pages/MarketPage/components/BestProducts/BestProducts.jsx
  src/pages/MarketPage/components/Product/Product.css
  src/pages/MarketPage/components/Product/Product.jsx
  src/pages/MarketPage/components/SalesProducts/SalesProducts.css
  src/pages/MarketPage/components/SalesProducts/SalesProducts.jsx
  src/reportWebVitals.js
  src/setupTests.js
  src/variable.css
Labels: 매운맛🔥, 미완성🫠

#162 [김영주] Sprint5
  .github/pull_request_template.md
  package-lock.json
  package.json
  public/favicon.ico
  public/index.html
  public/logo192.png
  public/logo512.png
  public/manifest.json
  public/robots.txt
  src/App.js
  src/App.jsx
  src/App.test.js
  src/api.jsx
  src/assets/fonts/PretendardVariable.woff2
  src/assets/images/ic_arrow_down.png
  src/assets/images/ic_heart.png
  src/assets/images/ic_search.png
  src/assets/images/logo_pandamarket.png
  src/assets/styles/mediaquery.css
  src/components/Header.css
  src/components/Header.jsx
  src/components/Main.css
  src/components/Main.jsx
  src/components/PageNavBar.jsx
  src/components/pageNavBar.css
  src/core/api.jsx
  src/index.css
  src/index.js
  src/logo.svg
  src/pages/AddItem/AddItem.jsx
  src/pages/Community/Community.jsx
  src/pages/Home/Home.jsx
  src/pages/Items/Items.jsx
  src/pages/Items/components/AllItemsContainer.jsx
  src/pages/Items/components/BestItemsContainer.jsx
  src/pages/Items/components/DropDownList.jsx
  src/pages/Items/components/ItemContainer.jsx
  src/pages/Signin/Signin.jsx
  src/reportWebVitals.js
  src/setupTests.js
  src/styles/global.css
  src/styles/mediaquery.css
Labels: 매운맛🔥, 미완성🫠

#166 [염성진] Sprint5
  package-lock.json
  package.json
  public/index.html
  src/App.css
  src/App.js
  src/App.test.js
  src/assets/images/icon/btn_icon/ic_arrow.png
  src/assets/images/icon/btn_icon/ic_favorite.png
  src/assets/images/icon/btn_icon/ic_mini_arrow.png
  src/assets/images/icon/btn_icon/ic_page_left_arrow.png
  src/assets/images/icon/btn_icon/ic_page_right_arrow.png
  src/assets/images/icon/btn_icon/ic_search.png
  src/assets/images/icon/btn_icon/ic_visibilty_off.png
  src/assets/images/icon/btn_icon/ic_visibilty_on.png
  src/assets/images/icon/ic_facebook.png
  src/assets/images/icon/ic_google.png
  src/assets/images/icon/ic_instagram.png
  src/assets/images/icon/ic_kakao.png
  src/assets/images/icon/ic_twitter.png
  src/assets/images/icon/ic_youtube.png
  src/assets/images/logo/Img_for_meta_tag.png
  src/assets/images/logo/logo.png
  src/assets/images/logo/mini_logo.png
  src/assets/images/mainPage/Img_home_bottom.png
  src/assets/images/mainPage/Img_home_for_sale_item.png
  src/assets/images/mainPage/Img_home_hot_item.png
  src/assets/images/mainPage/Img_home_item_search.png
  src/assets/images/mainPage/Img_home_top.png
  src/components/BestItem/BestItem.css
  src/components/BestItem/BestItem.js
  src/components/DropDown/DropDown.css
  src/components/DropDown/DropDown.js
  src/components/ItemsOnSale/ItemsOnSale.css
  src/components/ItemsOnSale/ItemsOnSale.js
  src/components/NavBar/NavBar.css
  src/components/NavBar/NavBar.js
  src/components/PaginationBar/PaginationBar.css
  src/components/PaginationBar/PaginationBar.js
  src/components/getApi.js
  src/index.css
  src/index.js
  src/logo.svg
  src/pages/home/Home.css
  src/pages/home/Home.js
  src/pages/items/Items.css
  src/pages/items/Items.js
  src/reportWebVitals.js
  src/setupTests.js
  src/styles/join.css
  src/styles/reset.css
Labels: 매운맛🔥, 미완성🫠

#169 [나윤주] Sprint5
  .prettierrc.json
  package-lock.json
  package.json
  src/assets/css/style.css
  src/assets/css/style.css.map
  src/assets/img/img-defalut.png
  src/assets/scss/components/_button.scss
  src/assets/scss/components/_pagination.scss
  src/components/AllProductList.js
  src/components/BestProductList.js
  src/components/Pagination.js
  src/components/ProductCard.js
Labels: 매운맛🔥

#184 [손재헌] Sprint6
  package-lock.json
  package.json
  public/index.html
  src/Main.js
  src/api.js
  src/api/api.js
  src/assets/ic_X.svg
  src/assets/ic_grayX.svg
  src/assets/ic_plus.svg
  src/assets/panda_blog-imagery-_21_Khajitted.jpg
  src/components/AddItemForm.css
  src/components/AddItemForm.js
  src/components/App.js
  src/components/LoadingImage.css
  src/components/LoadingImage.js
  src/components/header/Header.css
  src/components/header/LoginButton.css
  src/components/header/Nav.css
  src/components/header/Nav.js
  src/components/header/NavTab.css
  src/components/header/NavTab.js
  src/components/main/BestSection.js
  src/components/main/Items.css
  src/components/main/Items.js
  src/components/main/ItemsSection.css
  src/components/main/ItemsSection.js
  src/hooks/useAsync.js
  src/index.css
  src/index.js
  src/pages/AddItemPage.js
  src/pages/HomePage.js
  src/pages/ItemsPage.js
Labels: 매운맛🔥

#172 [나윤주] Sprint6
  src/App.js
  src/assets/css/style.css
  src/assets/css/style.css.map
  src/assets/img/Img_inquiry_empty.png
  src/assets/img/ic_X.svg
  src/assets/img/ic_X_blue.svg
  src/assets/img/ic_back.svg
  src/assets/img/ic_plus.svg
  src/assets/img/product/sample2.png
  src/assets/img/profile.png
  src/assets/scss/components/_card.scss
  src/assets/scss/components/_dropdown.scss
  src/assets/scss/components/_form.scss
  src/assets/scss/components/_icon.scss
  src/assets/scss/components/_index.scss
  src/assets/scss/components/_input-file.scss
  src/assets/scss/components/_loadingbar.scss
  src/assets/scss/components/_pagination.scss
  src/assets/scss/components/_tag.scss
  src/components/AllProductList.js
  src/components/FileInput.js
  src/components/Loadingbar.js
  src/components/Nav.js
  src/components/TagInput.js
  src/components/hooks/useAsync.js
  src/layout/Header.js
  src/layout/ItemMain.js
  src/pages/AddItem.js
  src/pages/AddItem.scss
  src/pages/Board.js
  src/pages/Board.scss
  src/pages/Faq.js
  src/pages/Faq.scss
  src/pages/Home.js
  src/pages/Home.scss
  src/pages/Items.js
  src/pages/Items.scss
  src/pages/Login.js
  src/pages/Login.scss
  src/pages/Notfound.js
  src/pages/Privacy.js
  src/pages/Signup.js
  src/pages/Signup.scss
  src/pages/privacy.scss
  src/utils/get-icon.js
Labels: 매운맛🔥

#185 [오정민] Sprint6
  package-lock.json
  package.json
  src/App.js
  src/Main.js
  src/assets/images/ic_plus.png
  src/components/Menu.css
  src/components/Menu.js
  src/components/Nav.css
  src/components/Nav.js
  src/components/additem/AddItemForm.css
  src/components/additem/AddItemForm.js
  src/components/additem/FileInput.css
  src/components/additem/FileInput.js
  src/components/additem/TextInput.css
  src/components/additem/TextInput.js
  src/components/items/AllProductList.css
  src/components/items/AllProductList.js
  src/index.js
  src/pages/AddItemPage.css
  src/pages/AddItemPage.js
  src/pages/ItemsPage.css
  src/pages/ItemsPage.js
Labels: 매운맛🔥, 미완성🫠

#199 [김주은] sprint5
  JS/common.js
  JS/login.js
  JS/signup.js
Labels: 매운맛🔥

#198 [김주은] sprint5
  package-lock.json
  package.json
  public/favicon.ico
  public/index.html
  public/logo192.png
  public/logo512.png
  public/manifest.json
  public/robots.txt
  src/App.css
  src/App.js
  src/App.test.js
  src/api.js
  src/assets/Page-1.svg
  src/assets/Page-2.svg
  src/assets/Page-3.svg
  src/assets/Page-4.svg
  src/assets/Page-5.svg
  src/assets/btn_left.svg
  src/assets/btn_right.svg
  src/assets/ic_arrow_down.svg
  src/assets/ic_heart.svg
  src/assets/ic_search.svg
  src/assets/ic_sort.svg
  src/assets/logo.svg
  src/components/AllItems.css
  src/components/AllItems.js
  src/components/BestItems.js
  src/components/Dropdown.js
  src/components/ItemList.js
  src/components/Navbar.css
  src/components/Navbar.js
  src/components/PaginationBar.js
  src/components/global.css
  src/index.css
  src/index.js
  src/logo.svg
  src/pages/Home.js
  src/pages/Market.js
  src/reportWebVitals.js
  src/setupTests.js
Labels: 매운맛🔥

#178 [김강우] sprint6
  .gitignore
  .prettierrc.json
  package-lock.json
  package.json
  src/App.js
  src/App.jsx
  src/Router.jsx
  src/assets/ic_X@3x.png
  src/assets/ic_blue_X@3x.png
  src/assets/ic_plus@3x.png
  src/components/Auth.jsx
  src/components/Cancel.jsx
  src/components/Header.jsx
  src/components/ItemFileInput.jsx
  src/components/ItemTop.jsx
  src/components/Pagination.jsx
  src/index.css
  src/index.js
  src/index.jsx
  src/pages/AddItem.jsx
  src/pages/Home.jsx
  src/pages/Items.jsx
  src/pages/Login.jsx
  src/pages/Signup.jsx
  src/styles/index.css
  src/styles/items.css
  src/styles/signup.css
  src/styles/styled/Additem.js
  src/styles/styled/Home.js
  src/styles/styled/index.js
  src/styles/styled/theme/theme.js
  src/utils/valid.js
Labels: 매운맛🔥

#191 [조규진] Sprint6
  package-lock.json
  package.json
  public/index.html
  src/API/itemApi.js
  src/App.js
  src/Layout/Header.css
  src/Layout/Header.jsx
  src/images/icons/ic_plus.svg
  src/images/icons/ic_x.svg
  src/images/icons/ic_x_act.svg
  src/index.css
  src/pages/AddItem/AddItemPage.css
  src/pages/AddItem/AddItemPage.jsx
  src/pages/AddItem/components/DeleteButton.jsx
  src/pages/AddItem/components/ImageUpload.css
  src/pages/AddItem/components/ImageUpload.jsx
  src/pages/AddItem/components/InputItem.css
  src/pages/AddItem/components/InputItem.jsx
  src/pages/AddItem/components/TagInput.css
  src/pages/AddItem/components/TagInput.jsx
  src/pages/home/HomePage.jsx
  src/pages/market/Market.css
  src/pages/market/Market.jsx
  src/pages/market/components/AllItemsSection.jsx
  src/pages/market/components/BestItemsSection.jsx
  src/pages/market/components/ItemCard.jsx
Labels: 미완성🫠

#192 [정원식] Sprint6
  .gitignore
  src/App.jsx
  src/assets/images/icons/ic_X.svg
  src/assets/images/icons/ic_union.svg
  src/components/items/BestItems/BestItems.jsx
  src/components/items/PaginationBar/PaginatinoBar.css
  src/components/items/PaginationBar/PaginationBar.jsx
  src/components/items/SellingItems/SellingItems.css
  src/components/items/SellingItems/SellingItems.jsx
  src/components/navigationBar/NavigationBar.css
  src/components/navigationBar/NavigationBar.jsx
  src/core/ui/buttons/Button/Button.css
  src/core/ui/buttons/Button/Button.jsx
  src/core/ui/inputs/ImageFileInput/ImageFileInput.css
  src/core/ui/inputs/ImageFileInput/ImageFileInput.jsx
  src/core/ui/inputs/TagInput/TagInput.css
  src/core/ui/inputs/TagInput/TagInput.jsx
  src/pages/addItems/AddItems.css
  src/pages/addItems/AddItems.jsx
  src/pages/api/Items.js
  src/pages/items/Items.css
  src/pages/items/Items.jsx
Labels: 매운맛🔥

#193 [이승현] Sprint6
  src/App.js
  src/api/api.js
  src/global.css
  src/pages/AddItemPage/AddItemPage.css
  src/pages/AddItemPage/AddItemPage.jsx
  src/pages/AddProductPage/AddProductPage.css
  src/pages/AddProductPage/AddProductPage.jsx
  src/pages/AddProductPage/components/FileInput/FileInput.css
  src/pages/AddProductPage/components/FileInput/FileInput.jsx
  src/pages/AddProductPage/components/TagInput/TagInput.css
  src/pages/AddProductPage/components/TagInput/TagInput.jsx
  src/pages/MarketPage/MarketPage.jsx
  src/pages/MarketPage/components/BestProducts/BestProducts.jsx
  src/pages/MarketPage/components/SalesProducts/SalesProducts.css
  src/pages/MarketPage/components/SalesProducts/SalesProducts.jsx
Labels: 매운맛🔥, 미완성🫠

#180 [장용한]Sprint6
  src/API/ItemAPI.js
  src/App.js
  src/ItemAPI.js
  src/Layout/Header.css
  src/Layout/Header.jsx
  src/Layout/UI/FileInput.css
  src/Layout/UI/FileInput.jsx
  src/images/icons/ic_X.svg
  src/images/icons/ic_plus.svg
  src/index.css
  src/index.js
  src/pages/AddItemPage/AddItemPage.css
  src/pages/AddItemPage/AddItemPage.jsx
  src/pages/AllCard.jsx
  src/pages/BestAllCard.jsx
  src/pages/BestCard.js
  src/pages/Card.js
  src/pages/CommunityFeedPage/CommunityFeedPage.css
  src/pages/CommunityFeedPage/CommunityFeedPage.jsx
  src/pages/HomePage/HomePage.css
  src/pages/HomePage/HomePage.jsx
  src/pages/ItemCard.jsx
  src/pages/LoginPage/LoginPage.css
  src/pages/LoginPage/LoginPage.jsx
  src/pages/MarketPage.jsx
  src/pages/MarketPage/MarketPage.css
  src/pages/MarketPage/MarketPage.jsx
  src/pages/MarketPage/components/AllCard.jsx
  src/pages/MarketPage/components/BestCard.jsx
  src/pages/MarketPage/components/ItemCard.jsx
  src/pages/MarketPage/components/style/AllCard.css
  src/pages/MarketPage/components/style/BestCard.css
  src/pages/utils.js
Labels: 매운맛🔥, 미완성🫠

#176 [염정훈] Sprint6
  .gitignore
  package-lock.json
  package.json
  public/images/i-close.png
  public/images/i-plus.png
  public/images/i-profile.png
  public/index.html
  src/api.js
  src/components/AddItem.js
  src/components/AllProduct.js
  src/components/App.js
  src/components/BestProduct.js
  src/components/Header.js
  src/components/Home.js
  src/components/Items.js
  src/components/ItemsPage.js
  src/components/Login.js
  src/components/NotFoundPage.js
  src/components/Signup.js
  src/css/reset.css
  src/css/style.css
  src/index.js
Labels: 매운맛🔥, 미완성🫠

#188 [김리나] Sprint6
  package-lock.json
  package.json
  public/index.html
  src/App.js
  src/assets/images/icons/arrow_left.svg
  src/assets/images/icons/arrow_right.svg
  src/assets/images/icons/ic_heart.svg
  src/assets/images/icons/ic_search.svg
  src/assets/images/icons/ic_sort.svg
  src/assets/images/logo/logo.svg
  src/global/Header/Header.css
  src/global/Header/Header.js
  src/index.js
  src/pages/Commu.js
  src/pages/Home.js
  src/pages/Login.js
  src/pages/Market.js
Labels: 미완성🫠

#196 [엄세환] sprint6
  package-lock.json
  package.json
  public/favicon.ico
  public/index.html
  public/logo192.png
  public/logo512.png
  public/manifest.json
  public/robots.txt
  src/App.css
  src/App.js
  src/App.test.js
  src/api/itemApi.js
  src/assets/images/icons/arrow_left.svg
  src/assets/images/icons/arrow_right.svg
  src/assets/images/icons/ic_heart.svg
  src/assets/images/icons/ic_search.svg
  src/assets/images/icons/ic_sort.svg
  src/assets/images/logo/logo.svg
  src/components/Layout/Header.css
  src/components/Layout/Header.jsx
  src/components/UI/DropdownList.css
  src/components/UI/DropdownList.jsx
  src/components/UI/PaginationBar.css
  src/components/UI/PaginationBar.jsx
  src/index.css
  src/index.js
  src/logo.svg
  src/pages/AddItemPage/AddItemPage.css
  src/pages/AddItemPage/AddItemPage.jsx
  src/pages/CommunityFeedPage/CommunityFeedPage.css
  src/pages/CommunityFeedPage/CommunityFeedPage.jsx
  src/pages/HomePage/HomePage.css
  src/pages/HomePage/HomePage.jsx
  src/pages/LoginPage/LoginPage.css
  src/pages/LoginPage/LoginPage.jsx
  src/pages/MarketPage/MarketPage.css
  src/pages/MarketPage/MarketPage.jsx
  src/pages/MarketPage/components/AllItemsSection.jsx
  src/pages/MarketPage/components/BestItemsSection.jsx
  src/pages/MarketPage/components/ItemCard.jsx
  src/reportWebVitals.js
  src/setupTests.js
  src/styles/global.css
Labels: 미완성🫠

#177 [정인재] Sprint6
  package-lock.json
  package.json
  src/Main.js
  src/api.js
  src/components/App.js
  src/components/Button.js
  src/components/FileInput.css
  src/components/FileInput.js
  src/components/Topbar.js
  src/index.js
  src/pages/AddItem.js
  src/pages/Additem.css
  src/pages/Items.css
  src/pages/Items.js
  src/pages/NotFound.js
Labels: 매운맛🔥
